//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Dehvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocManual
    {
        public long idDocManual { get; set; }
        public long idManual { get; set; }
        public long versionDoc { get; set; }
        public string ruta { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public bool estado { get; set; }
        public long idUsuarioCreador { get; set; }
    
        public virtual Manual Manual { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
