//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Dehvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manual()
        {
            this.DocManual = new HashSet<DocManual>();
        }
    
        public long idManual { get; set; }
        public long idProcedimiento { get; set; }
        public string nombre { get; set; }
        public string codReferencia { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocManual> DocManual { get; set; }
        public virtual Procedimiento Procedimiento { get; set; }
    }
}
