//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Dehvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedimiento()
        {
            this.Manual = new HashSet<Manual>();
        }
    
        public long idPrcoedimiento { get; set; }
        public long idDepartamento { get; set; }
        public string codProcedimiento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string objetivo { get; set; }
        public bool estado { get; set; }
        public long idUsuarioCreador { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manual> Manual { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
