//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Dehvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Departamento
    {
        public long idUsuarioDepartamento { get; set; }
        public long idUsuario { get; set; }
        public long idDepartamento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
